### PR TITLE
"set_delay" input for Delay Components

### PR DESCRIPTION
**Pull request by mc-oofert**
Added a "set_delay" input to the delay component.
This input (obviously) sets the components delay to the signals value.

`<input name="set_delay" displayname="connection.setdelay" />`
Appears to be working on multiplayer.

(ignore the ".gitignore")

### CODE REVIEW

**Comment by Working-Joe** [comment]
I'd love to see this change, but I think a few things are missing in this pull request. 

Your code does not seem to alter the `signalQueue` which stores the delayed signals. This could lead to problems as the size with which the queue is initialised depends on the delay. You'll see that if you now have a delay that is initially very short and you increase the delay, it can store too few signals, meaning that not all signals go through it. 

You'll also have to consider what you do with the signals that are currently in the queue. Currently existing signals just stay in the queue. This will cause weird behaviour if signals with a shorter delay are enqueued while signals with a large delay are still in the queue.

**Comment by mc-oofert** [comment]
> I'd love to see this change, but I think a few things are missing in this pull request.
> 
> Your code does not seem to alter the `signalQueue` which stores the delayed signals. This could lead to problems as the size with which the queue is initialised depends on the delay. You'll see that if you now have a delay that is initially very short and you increase the delay, it can store too few signals, meaning that not all signals go through it.
> 
> You'll also have to consider what you do with the signals that are currently in the queue. Currently existing signals just stay in the queue. This will cause weird behaviour if signals with a shorter delay are enqueued while signals with a large delay are still in the queue.

Done, I think???

**Comment by Working-Joe** [comment]
I think it's still incomplete. Now it clears the queue, but it still doesn't change the queue size.

**Comment by mc-oofert** [comment]
> I think it's still incomplete. Now it clears the queue, but it still doesn't change the queue size.

Line 86 and 40 says otherwise

**Comment by Working-Joe** [comment]
You're right, the queue size should be fine now! Now that you clear it setting `Delay` should be enough.

Did find one last bug. You currently clear the queue before you clamp the delay. This means that if your delay is at one of the clamped edges, it will be reset when a value outside the clamp in sent into `set_delay`.

e.g. wiring 70 into the delay will cause it to reset every frame because 70 != 60 and the stored delay is clamped to 60.

**Comment by mc-oofert** [comment]
Done

**Comment by Regalis11** [comment]
Thank you for the PR! Finally got around to merging this to our private repo.

**Pull request closed without merging**
