### PR TITLE
Add "water_%" output signal to water detector

### PR DESCRIPTION
**Pull request by rasicz**
#3904

### CODE REVIEW

**Comment by Regalis11** [comment]
This causes a crash if the detector is outside a hull

**Comment by rasicz** [comment]
Added condition to test if hull is not null.

**Comment by Regalis11** [comment]
Some additional issues:
- The output is inconsistent, because the conversion to string is culture-sensitive (e.g. the decimal separator can be a dot or a comma depending on the user's language).
- The format of the output can vary wildly: e.g. "4", "1.45E-6f", "8.34561"... I think the output would be much easier to use if it was an integer.

**Comment by rasicz** [comment]
This shoud hopefully fix all issues.

**Comment by Regalis11** [comment]
Thanks! Couldn't spot any additional problems, merged this to our private repo now.

**Pull request closed without merging**
