### PR TITLE
Added a tickbox to terminals to use a monospaced font

### PR DESCRIPTION
**Pull request by Working-Joe**
## Functional additions

There is a lot of interest in the wiring community for building circuits involving the terminal for user input. However, the usage of terminals is limited by the proportional font, as it is impossible to make good looking interfaces without knowing the width of the displayed text. 

This problem is solved in this PR by adding a tickbox to terminals which if toggled makes them use a monospaced font.

An example of the difference between a terminal using the default font and a terminal using the monospaced font is shown in the figure below.

Whether or not a terminal uses the monospaced font depends on whether they have the corresponding tickbox ticked, which can only be changed in the editor and is off by default.

## Code and XML changes

The code changes in this pull request are fairly self explanatory. They involve adding a ScalableFont for the monospaced font in `GUI.cs` and `GUIStyle.cs`, the addition of the editable boolean in `terminal.cs` in the SharedSource and a code change to make the terminal use the monospaced based on the boolean in `terminal.cs` in the ClientSource.

The addition of a font of course also requires changes to the style.xml. 

```xml
		<MonospacedFont file="Mods/MonospacedFont/source-code-pro/SourceCodePro-Semibold.ttf">
			<Size maxresolution="1024,768" size="12" />
			<Size maxresolution="1280,800" size="14" />
			<Size maxresolution="1920,1080" size="16" />
			<Size maxresolution="2048,1440" size="18" />
			<Size maxresolution="2560,1600" size="18" />
			<Size size="18" />
		</MonospacedFont>
```

The added zip archive includes the files for a mod that overrides the UIStyle with the monospaced TTF font used in the above image (which should be free for commercial use). 

[MonospacedFont.zip](https://github.com/Regalis11/Barotrauma/files/6282005/MonospacedFont.zip)

### CODE REVIEW

**Comment by Ecchi-Ki-Senpai** [comment]
Please add this to the game

**Comment by Psyduckdeluxe** [comment]
Please add this to the game more!

**Comment by Working-Joe** [comment]
There is also interest in adding a monospaced font to labels (which includes text displays iirc), if desired I could extend this PR to include that.

**Comment by alexstratford** [comment]
Please add this

**Comment by Regalis11** [comment]
Thank you for the PR! Merged to our private repo now.

**Pull request closed without merging**
