### PR TITLE
Expansion of Barotrauma's logic system.

### PR DESCRIPTION
**Pull request by kuraiookami**
This is the first time I have tried to contribute to a Github project.
If I have done something wrong with git please explain my mistake so I can learn.

Changed:
- AdderComponent and children can clamp their output
- Powercontainer signals for charge,charge% and charge rate

Added:
- ColorComponent: Dynamic signals for light set_color inputs
- MemoryComponent: Stores and sends a signal that is edge latched
- DivideComponent: Standard division
- MultiplyComponent: Standard multiplication
- SubtractComponent: Standard subtraction
- XorComponent: Exclusive or
- EqualsComponent: Equals comparison
- GreaterComponent: Greater than comparison

### CODE REVIEW

**Comment by Regalis11** [comment]
Nice work, these would be useful for sure! I didn't test these yet but I believe there's at least one small issue: I think you should be using invariant culture when parsing floats or converting them to strings, otherwise the same circuit may behave differently depending on which decimal separator the player's system is using.

I'll take a closer look at this and merge it as soon as I have my hands a little less full with getting the dev branch ready for closed beta. :)

**Comment by kuraiookami** [comment]
I tested this in-game in every way I could think of but I missed that.
This fault is my own doing, every time I have used GitHub code in the past it has been for personal modifications or learning. I have never really thought about the consequences of things like decimal separators that are foreign to me.

I am unsure of the proper way to test that. Does changing the Windows region->format settings count as sufficient? Or are there other things that need to be done to test this in a complete manner?

**Comment by Regalis11** [comment]
Yeah, that's something very easy to miss (I've done the same mistake several times even after realizing it can make a difference in this game). :)

I believe this could be tested by changing your region to something where a decimal comma is used (see https://en.wikipedia.org/wiki/Decimal_separator). The problem is pretty easy to fix, you just need to use CultureInfo.InvariantCulture when parsing the float signals and when converting the result of the calculation back to a string.

**Comment by CommanderMark** [comment]
Seems like this addresses a lot of #392.

**Comment by rico6822** [comment]
Can we turn "to do" stuff in here into task list so we can know what remains undone?

**Comment by Regalis11** [comment]
Added in 26e89c6

**Pull request closed without merging**
