### PR TITLE
remove waitforkeyhit check

### PR DESCRIPTION
**Pull request by Tsunder**
i'm sure this will have no unforeseen consequences

### CODE REVIEW

**Comment by cshingle** [comment]
It would be nice to not have to push the anykey to go to the main menu every time the game starts.

**Comment by Regalis11** [comment]
What's the reasoning behind this change? I think it's important to wait for the input so a round doesn't start while your afk if you go and do something else while it loads. Even though it isn't that important in the main menu, I think it's good that all loading screens behave consistently.

And what's the purpose of the waitKeyHit parameter in the ShowLoading menu and the waitForKeyHit field in GameMain now if they're not used for anything?

**Comment by Jade-Harleyy** [comment]
I think a better way to implement this would be to make it toggleable in the settings menu, so players can choose whether they want to have to press a key to close loading screens or not.

**Comment by Tsunder** [comment]
The primary reasoning was just to remove the initial game load key wait (that goes to main screen)

I forgot that wait for key is used elsewhere (i.e., single player mode)

**Pull request closed without merging**
