### PR TITLE
Updated and refactored how items and characters are chosen for intera…

### PR DESCRIPTION
**Pull request by Faerdan**
…ctions in the world. The new system has more precision, with items under the cursor taking priority (this helps with small items which are in front of large items). A new method CanInteractWith(Item) has been added to the Character class which does all validation of interaction with items, including new distance calculations based on bounding boxes. This gives more consistency in selecting and interacting with all sizes and shapes of items. Because of this pickdistance has been removed from all items (in their XML config files) and the default PickDistance for all items is now 120.

### CODE REVIEW

**Comment by Faerdan** [comment]
JAG (on Discord) found an issue, the Hatch button inside of the docking hatch on the Aegir cannot be clicked, for some reason on my implementation the physics Raycast is failing to hit the button item. I will look into this further in the morning.

**Comment by Regalis11** [comment]
It seems that the issue on Aegir is due to the button being in a different submarine (the docked shuttle). CanInteractWith doesn't work correctly if the item is not inside the same sub as the character, so now it's also impossible to press airlock buttons from the outside. Transforming the position of the item to the same coordinate system as the player before doing the raycast should fix this, something along the lines of:
`if (Submarine == null && item.Submarine != null)
{
    //character is outside, item inside
    itemPos += item.Submarine.SimPosition;
}
else if (Submarine != null && item.Submarine == null)
{
    //character is inside, item outside
    itemPos -= Submarine.SimPosition;
}
else if (Submarine != item.Submarine)
{
    //character and the item are inside different subs
    itemPos += item.Submarine.SimPosition;
    itemPos -= Submarine.SimPosition;
}`

**Comment by Faerdan** [comment]
Ah brilliant, thanks for clearing that up.

This week got very busy, but I should be able to implement the fix this evening.

**Comment by Faerdan** [comment]
I am going to create a new pull request for this update.

**Pull request closed without merging**
