### PR TITLE
Reactor can be controlled with movement keys

### PR DESCRIPTION
**Pull request by JJRcop**
This happens when the mouse is near the control bars or is currently dragging one of them.

Left and Right (default A and D) control the Fission rate
Up and Down (default W and S) control the Turbine output

Run (Default LeftShift) quadruples the speed.

This is where the mouse zone is, similar to the steering menu.
image

I put the scrollbars into a GUILayoutFrame so their position was slightly shifted, I tried to get it close enough. Notably the labels are affected.

**OLD**
image

**NEW**
image

### CODE REVIEW

**Comment by TheHellFireo** [comment]
should have PR'ed it into the dev version

**Comment by JJRcop** [comment]
Changed base to dev branch and now controls still work if you're dragging one of the bars even if you move the mouse out of the detection box.

**Comment by Regalis11** [comment]
Nice, this looks very useful. :) We haven't had time to test and merge it yet because we have our hands full with more critical fixes atm, but we'll take a look once the more high-priority stuff is out of the way.

**Comment by Regalis11** [comment]
Merged in https://github.com/Regalis11/Barotrauma-development/commit/bb5b807aa97559e4de3b3670e038ab4d1a301db8 (private repo)

**Pull request closed without merging**
